### PR TITLE
Add a simple geepack container

### PR DESCRIPTION
**Pull request by thebigcorporation**

### CODE REVIEW

**Review by kscott-1 — APPROVED** [review]
looks good

**Comment by kscott-1** [comment]
I do wonder if we should include the tidy verse in the r base image. For my own use case, I only manipulate data with dplyr & friends. Base R is just not comparable. If I had a 'geepack' file to run, there is good chance I am also using the tidyverse. This is true of just about any simple packages like this. Worth thinking about I think - I doubt it would blow up the base build.

**Comment by thebigcorporation** [comment]
With R in general, there really is a hierarchy of containers that don’t need to be rebuilt separately, just more stuff added, which hardly takes any space.

The capability the make file needs, is only to associate a specific base image (rather than always hihg-um/r) for a given image.

That would eliminate 90% of the bloat, and would allow factoring out as many layers of common dependencies as divergent paths there are.

that said, initially, I ee no issue in adding tidyverse - it is a recommended package anyways

**Comment by kscott-1** [comment]
Yeah sounds good, for geepack in particular, most of the tidyverse packages seem to be dependencies anyway. Though I think broadly we should just consider the ecosystem to be part of 'base R'. Not sure what the size comparisons are, but I doubt it is much different.

**Pull request merged**
