### PR TITLE
[WIP]: STAAR

### PR DESCRIPTION
**Pull request by thebigcorporation**
Dockerize STAAR, MultiSTAAR and MetaSTAAR

- I want to add a number for bulld infra improvements before merging this, there will be a few rebases as I move the trivial cleanups down to the main branch.

### CODE REVIEW

**Comment by kscott-1** [comment]
I am going to do some research on all of this today.

Should we be mixing:
 - Ubuntu binaries, locked to version X
 - dev versions from github

**Comment by thebigcorporation** [comment]
Worse yet, there are additional fixed-version libraries “vendored” within specific packages.

No we should not, or they should not.

**Comment by kscott-1** [comment]
Yes - that means some additional care needs to be had here. Possibly rethinking the whole approach. As it stands we are doing exactly that.

**Comment by thebigcorporation** [comment]
I will fix the build issue - it was just too many hours yesterday - like 16; needs to change BASE_IMAGE to BASE

**Comment by thebigcorporation** [comment]
It is part of a larger break-down of the tags, which is still only partially complete, so that the labels can pick up the right values. See docker-utils and docker-analytics. Both of these still need to figure out how to set both the container version and the app version; where currently we only set the container version. In addition, if the number of commits (--count) from a named tag, live v2.5.0 is "0", it does not need to include the git hash, and can just be hihg-um/app:v2.5.0. This will get in all in good time.

**Comment by thebigcorporation** [comment]
docker inspect <image> will show the standard labels that we set. Labels set in the base image can be, but do not need to be overridden, as needed.

**Comment by kscott-1** [comment]
I am going to suggest we check out pak (https://github.com/r-lib/pak) for all R related package installations & Pull R down directly from https://www.r-project.org/

I think it is a step to significantly improve the installs

**Comment by thebigcorporation** [comment]
That still will not fix the vendored packages, take a look….

**Pull request closed without merging**
